### PR TITLE
File headers

### PR DESCRIPTION
**Pull request by julianhyde**
Make sure that the file headers and NOTICE file are correct (per the wishes of the copyright owners)

Add Checkstyle rules to ensure that the headers remain correct.

### CODE REVIEW

**Comment by julianhyde** [comment]
@mbudiu-vmw Can you complete this pull request? You need to change headers to something that VMWare is happy with (assuming that they are the copyright owner).

It would be simpler if it were a single license throughout - Apache or MIT.

For the small amount of code for which I am the copyright owner, I am happy with whatever you decide.

**Comment by mbudiu-vmw** [comment]
I am working on reorganizing the code to be extensible, so that other users can register new executors and command-line options easily. 

I will work on the headers too, but I guess that should be part of a separate PR (this one). If you want just one license it's probably easiest to just use MIT. That's the license of the original code, and it seems to require to be quoted in any derivative work.

**Comment by julianhyde** [comment]
Regarding extensibility. In ed96c90d0674db78fb8d9668b6cef08cb01aa8e1 I made the `Main` class instantiable. That allows us to turn off the call to `System.exit` (which makes unit testing impossible) and would allow extensibility such as passing an "executor factory" to the constructor.

**Comment by julianhyde** [comment]
Happy to go with the MIT license.

Can you modify this PR with checker headers you want?

Yes, the extensibility changes should be a separate PR. I suggest that you fork the repo in GitHub so that your PR is from a branch in your fork, not the main hydromatic repo.

**Pull request closed without merging**
