### PR TITLE
Implement and test flags -x and -n. Update README with current usage.

### LINKED ISSUE #17: The -x flag (stop at first bug encountered) does not work properly.

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
Fixes #17

### CODE REVIEW

**Comment by julianhyde** [comment]
There are some checkstyle violations. Can you please run `./mvnw clean verify` before submitting.

I enabled CI on pull requests, so these errors should show up automatically in future.

**Comment by mbudiu-vmw** [comment]
The problem with mvnw is that I get the error described in #19

**Comment by julianhyde** [comment]
Use JDK 11 or higher and you should be OK.

**Comment by mbudiu-vmw** [comment]
We should add this information to the README. I will add to the PR.

**Comment by julianhyde** [comment]
It is already in the README.

**Comment by mbudiu-vmw** [comment]
This is what I see: `You need Java (8 or higher) and Git.`

**Comment by mbudiu-vmw** [comment]
I see: the `-Dcheckstyle`
Got it

**Pull request closed without merging**
