### PR TITLE
Extensible testing framework

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
@julianhyde I apologize for the larger PR.
This makes the framework more modular to enable others to add new tests, probably by writing new main functions.
The code in this commit contains tests for hsqldb and postgres as examples of JDBC extensions.
For this purpose I included the drivers as dependencies in the pom for now for testing.
I have also removed Calcite and JCommander as dependencies.

The amusing thing is that neither of these databases actually passes all tests... some of the failures may be test bugs, but at least hsqldb has some problems that I plan to file bugs against.
I am not sure if I got all the metadata stuff right, like licenses and checker configurations, but hopefully we can iterate from this point.

### CODE REVIEW

**Comment by julianhyde** [comment]
Your change undoes a lot of my changes. (E.g. enabling checkstyle, and fixing format to match, and making Main instanatiable.) I don't know whether you disagree with them, but I thought they were improvements, and I spent quite a few hours making them.

**Comment by mbudiu-vmw** [comment]
I should not have touched checkstyle.
Main should still be Instantiate, but I think it's called execute.

**Comment by mbudiu-vmw** [comment]
My changes are only to java files and to the pom file, which changes affect the checkstyle?
I have moved the files to a different package, that's the biggest change.
The formatting has been performed by the IDE I am using (Intellij), I have no problems changing the configuration.

**Comment by zabetak** [comment]
Note that in https://github.com/hydromatic/sql-logic-test/pull/11 I removed the download logic of test files from external repos by bundling everything within. If you disagree with the approach lets discuss there.

**Comment by mbudiu-vmw** [comment]
> Note that in #11 I removed the download logic of test files from external repos by bundling everything within. If you disagree with the approach lets discuss there. I am mentioning this here since I see that this PR touches and changes related code.

The test files seem to be very stable so this makes sense.

**Comment by mbudiu-vmw** [comment]
@julianhyde I guess you are actually referring to #6. I have built this stuff on main.
I didn't look at #6 prior to making these changes, I guess the PR name made me think that it only dealt with headers.
I have no problem "rebasing" this on #6, but it may be faster to have some tool apply the checkstyle automatically than to resolve all the conflicts by hand.

**Comment by julianhyde** [comment]
#6 was originally a single commit, and didn't have many changes. Maybe I screwed things up when I force-pushed to main, and the "Checkstyle" commit was accidentally included.

This patch captures the intent of this PR: https://github.com/hydromatic/sql-logic-test/commit/9b1d626c27ee048a8525acbe44097cbe9974e0ca.patch

**Comment by mbudiu-vmw** [comment]
I am not working on anything now until we merge this pr. The subsequent ones will be smaller.

**Comment by julianhyde** [comment]
OK, thanks. I'll work on this tomorrow, and let you know when the repo is available. But please assume that history will be completely rewritten.

**Pull request closed without merging**
