### PR TITLE
Release 0.2

### PR DESCRIPTION
**Pull request by julianhyde**
@mihaibudiu and @zabetak, Please review this PR as a candidate for release 0.2. The latest commit contains release notes. The previous commits are those in #25, re-organized slightly.

### CODE REVIEW

**Review by mihaibudiu — APPROVED** [review]
Looks great. Thank you.

**Comment by zabetak** [comment]
I pushed a few things in https://github.com/apache/calcite/pull/3145 and tried to run the `TestCalcite` using this 0.2 RC from maven local but I run into some classpath related problem:
```
./gradlew :plus:test --tests TestCalcite -PenableMavenLocal

> Task :plus:test FAILED
FAILURE   0.0sec, org.apache.calcite.slt.TestCalcite > testRunCalcite()
    java.nio.file.NoSuchFileException: file:/home/stamatis/.m2/repository/net/hydromatic/sql-logic-test/0.2/sql-logic-test-0.2.jar!/test/select1.test
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
        at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
        at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
        at java.nio.file.Files.readAttributes(Files.java:1737)
        at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
        at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
        at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
        at java.nio.file.Files.walkFileTree(Files.java:2662)
        at java.nio.file.Files.walkFileTree(Files.java:2742)
        at net.hydromatic.sqllogictest.Main.execute(Main.java:69)
        at org.apache.calcite.slt.TestCalcite.launchSqlLogicTest(TestCalcite.java:56)
        at org.apache.calcite.slt.TestCalcite.testRunCalcite(TestCalcite.java:65)
```
I don't have more time to look into this today but I would suggest to wait till we get this test in plus module to pass.

**Comment by julianhyde** [comment]
@zabetak I agree; this looks like a show-stopper, and we should hold the release until it is resolved. I built a 0.2-SNAPSHOT jar and the `/test/select1.test` file seems to be present, so I'm not sure what's going on.

**Comment by mihaibudiu** [comment]
This error happens if you try to invoke the program from the jar:
```
exec java -classpath target/sql-logic-test-0.2-SNAPSHOT.jar net.hydromatic.sqllogictest.Main -e none select1.test
Exception in thread "main" java.nio.file.NoSuchFileException: file:/home/mbudiu/git/sql-logic-test/target/sql-logic-test-0.2-SNAPSHOT.jar!/test/select1.test
```

Since the files are archived in the jar I am guessing that walkFileTree does not know how to decompress them.

**Comment by mihaibudiu** [comment]
There is at least one more fix necessary besides fixing the jar file access problem: one needs a handle to the ExecutionOptions to register the CalciteExecutor. I will submit a separate commit for this problem.

**Comment by julianhyde** [comment]
@mihaibudiu, Let me know when you are ready for me to make a release.

**Comment by mihaibudiu** [comment]
From my point of view this is ready.

**Comment by julianhyde** [comment]
OK, I'll make the release over the weekend.

**Comment by julianhyde** [comment]
@mihaibudiu, When you say "this is ready" are you assuming that I include #35 in the release? It is approved but not yet merged.

**Comment by julianhyde** [comment]
Fixed in 4bde68b8563f471300f95bb0f14f35400d577be9.

**Pull request merged**
